### ISSUE TITLE
Infinite loop after log in without pretty urls

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/twofa#11]
Steps to reproduce:

- Disable pretty URLs https://docs.humhub.org/docs/admin/installation/#pretty-urls
- Try to log in with enable 2FA
- Inifite loop because here https://github.com/humhub/humhub-modules-2fa/blob/master/Module.php#L50 the condition `Yii::$app->getRequest()->getUrl() === TwofaUrl::ROUTE_CHECK` is not correctly.

Here https://github.com/humhub/humhub-modules-2fa/commit/923495c9c55fa5949554d6afa3e9e9c8039b331a#diff-074f64cd19bc13bc527290951a58a65cb54f2f35a43ce5bf95e5dbb20b4d297dR50 I changed that but it was not enough, we should find another better solution.

Also I think same issue exists in the core feature "Must change password on next login" in the method `User::isMustChangePasswordUrl()` https://github.com/humhub/humhub/blob/develop/protected/humhub/modules/user/components/User.php#L237

**Comment by ArchBlood** [comment]
https://github.com/humhub/twofa/commit/14c54ad0929be636d49582b73ea17d67523a2cba breaks PrettyUrl though, I was forced to disable PrettyUrl to stop loops 🤔

**Comment by ArchBlood** [comment]
Also appears in the Legal module, so I'm sure that it probably occurs in modules that create pages

A simple solution till a definite fix is made would be to disable PrettyUrl when this happens then reenable it

**Comment by luke-** [comment]
@yurabakhtin Can you please take a look?

**Comment by yurabakhtin** [comment]
@ArchBlood 

> https://github.com/humhub/twofa/commit/14c54ad0929be636d49582b73ea17d67523a2cba breaks PrettyUrl though, I was forced to disable PrettyUrl to stop loops 🤔

Are you sure the problem in the commit?

Probably the problem only in the Legal module, please check your module "Legal" has the latest files version, especially this fix https://github.com/humhub-contrib/legal/pull/30/files where we had a infinite loop with enabled user option "Force password change upon next login".

**Comment by ArchBlood** [comment]
> @ArchBlood 
> 
> > https://github.com/humhub/twofa/commit/14c54ad0929be636d49582b73ea17d67523a2cba breaks PrettyUrl though, I was forced to disable PrettyUrl to stop loops 🤔
> 
> Are you sure the problem in the commit?
> 
> Probably the problem only in the Legal module, please check your module "Legal" has the latest files version, especially this fix https://github.com/humhub-contrib/legal/pull/30/files where we had a infinite loop with enabled user option "Force password change upon next login".

I'm pretty sure it was the latest version of twofa on the marketplace

**Comment by ArchBlood** [comment]
Easy way to reproduce was to enable the module then use the email option then logout and try logging back in, the check email loops till PrettyUrl is disabled

**Comment by yurabakhtin** [comment]
@luke- Can you reproduce this?

**Comment by luke-** [comment]
@ArchBlood @yurabakhtin For me the module works with the latest core `Master` branch, both with and without PrettyUrls. Hmmm....
