### ISSUE TITLE
TBOT passwords cannot be enabled in versions 1.0.1 and 1.0.2

### ISSUE THREAD

**Issue by smashm** [humhub/twofa#22]
I use the module since 1.0 and after the updates »Time-based one-time passwords« is disabled and there is no chance to enable it. (I'v updated to 1.0.1 a few days ago, but didn't notice, that this behavior obviously started with that version.)

![Bildschirmfoto 2021-05-11 um 09 41 36](https://user-images.githubusercontent.com/60502320/117780459-ee8f8900-b23f-11eb-8a44-cd0b26297793.png)

![Bildschirmfoto 2021-05-11 um 09 41 55](https://user-images.githubusercontent.com/60502320/117780484-f51e0080-b23f-11eb-968b-06b527c522ed.png)

I've tested in on two different systems, both HH 1.8.2, with PHP 8.0.5 and PHP7.4.9. All caches cleared, original community theme, different browsers. Even after a complete deinstalling and a fresh 1.0.2 install it doesn't work. Only working way is to use v 1.0.

**Comment by yurabakhtin** [comment]
@luke- The TBOT passwords driver is disabled if composer files are not found, I installed them manually by run `composer install` from the module folder. Should I implement to install them automatically somehow when the module is installed from Marketplace?
