### ISSUE TITLE
QR-code is rendered twice after aborting new request

### ISSUE THREAD

**Issue by smashm** [humhub/twofa#25]
It's only a small blemish, but reproducible. 

TOTP is activated and a working QR-code is already stored. If a new code is requested (by mistake or deliberately), but the process is aborted, the image of the old code is rendered twice or additionally again.

![Bildschirmfoto 2021-05-18 um 09 12 39](https://user-images.githubusercontent.com/60502320/118610978-a2eb5b00-b7bc-11eb-82cd-4c410982d122.png)

![Bildschirmfoto 2021-05-18 um 09 13 24](https://user-images.githubusercontent.com/60502320/118610395-032dcd00-b7bc-11eb-98bf-5c0892b34aa9.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/twofa/pull/26.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
