### ISSUE TITLE
QR Code is not displayed when "Name of the application" contains special character

### ISSUE THREAD

**Issue by arnogramatke** [humhub/twofa#27]
HumHub 1.8.2
Two-Factor Authentication Module 1.0.3

In my installation the "Name of the application" contains an apostrophe (SHIFT+OPT+# on macOS). With this name, the QR Code to enable 2FA is not displayed. When I remove the apostrophe, the QR Code is displayed and I can activate 2FA for my account.

**Comment by yurabakhtin** [comment]
@luke- I have tested the apostrophe char `‹` (SHIFT+OPT+# on macOS), yes we had the bug, but it was already fixed in PR https://github.com/humhub/twofa/pull/23.

**Comment by luke-** [comment]
@yurabakhtin Oh ok, I hadn't released it yet. v1.0.4 is now released!

**Comment by arnogramatke** [comment]
Just updated 1.0.4. It works now. Thanks!
