### ISSUE TITLE
Button "Log out" doesn't prevent pjax

### ISSUE THREAD

**Issue by yurabakhtin** [humhub/twofa#29]
@luke- Why did you modified the button "Log out" here https://github.com/humhub/twofa/commit/7375d22#diff-6b50c5c79652c49abaff914c86163ba66bb7e98736f436d6d440a588b365ab6aR45 ?

<img width="846" alt="button_logout" src="https://user-images.githubusercontent.com/6995524/126267161-6bf77c60-2b2f-475d-a842-14b6d4bdd600.png">

At least the attribute `'data-pjax' => false` is wrong, because correct is `'data-pjax-prevent' => 1`.

**Comment by yurabakhtin** [comment]
@luke- 

> At least the attribute `'data-pjax' => false` is wrong, because correct is `'data-pjax-prevent' => 1`.

PR https://github.com/humhub/twofa/pull/30

**Comment by luke-** [comment]
@yurabakhtin Thanks!
