### ISSUE TITLE
Impersonate not available if two-factor authentification is enable

### ISSUE THREAD

**Issue by funkycram** [humhub/twofa#31]
### What steps will reproduce the problem?

Go in "Administration" -> "Users"
Try to impersonate a user that have two-factor authentification enabled

### What is the expected result?

Be logged in tothis user.

### What do you get instead?

This form:
Two-factor authentication
A confirmation code hast just been sent to your email address. Please enter the code from the email in order to proceed.

And a mail sent to the user...

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.9.1

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub/twofa/pull/32.
This bug was only when an impersonated user was started to login but didn't enter 2fa code.

**Comment by funkycram** [comment]
Thanks @yurabakhtin !
