### ISSUE TITLE
Add Trusted network option

### ISSUE THREAD

**Issue by fsainovich** [humhub/twofa#33]
Please, add Trusted network option to allow access without 2fa.

**Comment by Soundwave2142** [comment]
@luke- can you specify how exactly this needs to be completed?

If I understand correctly, on page where you enter a code, add a check box. But should it be "do not ask again for this browser" (if so, does additional config required for amount of days?). or should it be "do not ask for this user" which will disable auth for user (again, limited, not limited? config required? how to re-enable?)?

**Comment by luke-** [comment]
@Soundwave2142 Yes sure :-) In the admin configuration settings of the module, the administrator should be able to specify comma separated, multiple IPs or subnets. If the login comes from one of these IPs/subnets no two factor login should be necessary. So a simple one factor login should be sufficient. 

The remember me is another issue here: https://github.com/humhub/twofa/issues/16

**Comment by Soundwave2142** [comment]
@luke- Do you want me to work on #16? Seems like a 20 minutes work and can be nice addition to release with this functionality.

**Comment by fsainovich** [comment]
> @Soundwave2142 Yes sure :-) In the admin configuration settings of the module, the administrator should be able to specify comma separated, multiple IPs or subnets. If the login comes from one of these IPs/subnets no two factor login should be necessary. So a simple one factor login should be sufficient.
> 
> The remember me is another issue here: #16

Correct. Do not need 2FA for a trusted network, like private/inside/intranet company network. Only access from internet (like home office) needs 2FA.
