### ISSUE TITLE
Remember browser & email verifcation

### ISSUE THREAD

**Issue by Semir1212** [humhub/twofa#50]
HH 1.12
2FA 1.0.7

- Set verification to email
- Activate 'remember browser'
- Logout & repeat login process
- User is logged in, verification email is sent nonetheless

![image](https://user-images.githubusercontent.com/38326726/200026826-b7f66a82-a7f0-4dfb-b6a6-cd206287f219.png)

**Comment by luke-** [comment]
@yurabakhtin Thanks

@Semir1212 Fixed in module 1.1.0
